language: rust
matrix:
  allow_failures:
    - rust: nightly
  include:
  - os: linux
  - os: osx
  - os: windows
  - rust: stable
  - rust: beta
  - rust: nightly
  - rust: 1.30.0
  - env: DEPLOY=1
    os: osx
    script:
      - cargo install --debug cargo-make
      - cargo make binary-distribution-ci-flow --env TARGET=x86_64-apple-darwin
  - env: DEPLOY=1
    os: windows
    script:
      - cargo install --debug cargo-make
      - cargo make binary-distribution-ci-flow --env TARGET=x86_64-pc-windows-msvc
  - env: DEPLOY=1
    os: linux
    script:
      - cargo install --debug cargo-make
      - cargo make binary-distribution-ci-flow --env TARGET=x86_64-unknown-linux-musl
    addons:
      apt:
        packages:
        - musl-tools
env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="-C link-dead-code"
    - CARGO_MAKE_RUN_CODECOV=true
script:
  - cargo install --debug cargo-make
  - cargo make ci-flow
deploy:
  api_key:
    secure: <API KEY GOES HERE>
  file_glob: true
  file: cargo-make-*.zip
  on:
    condition: $DEPLOY = 1
    tags: true
  skip_cleanup: true
